go: &go
  image: golang
  working_dir: /go/src/github.com/mattes/migrate
  volumes:
    - $GOPATH:/go
go-test:
  <<: *go
  command: sh -c 'go get -t -v ./... && go test -v ./...'
  links:
    - postgres
    - mysql
    - cassandra
go-build:
  <<: *go
  command: sh -c 'go get -v && go build -ldflags ''-s'' -o migrater'
  environment:
    CGO_ENABLED: 1
postgres:
  image: postgres
mysql:
  image: mysql
  environment:
    MYSQL_DATABASE: migratetest
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
cassandra:
  image: cassandra:2.2
